Repository kubernetes-sigs/ingress2gateway, pull requests merged in 2023-06, with the labels that each got.

#25 Add LiorLieberman to reviewers
  OWNERS
Labels: approved, cncf-cla: yes, size/XS, lgtm

#29 Fix pull-ingress2gateway-verify presubmit
  pkg/i2gw/aggregator.go
  pkg/i2gw/aggregator_test.go
  pkg/i2gw/ingress2gateway.go
Labels: approved, size/M, kind/cleanup, cncf-cla: yes, lgtm, ok-to-test

#26 Add support for JSON & YAML output types
  Makefile
  README.md
  cmd/print.go
  cmd/print_test.go
  cmd/root.go
  go.mod
  go.sum
  pkg/i2gw/ingress2gateway.go
Labels: kind/feature, approved, size/L, cncf-cla: yes, lgtm
