Repository kubernetes-sigs/ingress2gateway, pull requests merged in 2023-12, with the labels that each got.

#97 fix: ingress rules order is preserved
  go.mod
  go.sum
  pkg/i2gw/providers/common/converter.go
  pkg/i2gw/providers/common/utils.go
  pkg/i2gw/providers/common/utils_test.go
  pkg/i2gw/providers/ingressnginx/canary.go
Labels: kind/bug, approved, size/XL, cncf-cla: yes, lgtm

#98 deps: gateway API bumped to v1.0.0
  .github/workflows/build.yaml
  cmd/print.go
  go.mod
  go.sum
  pkg/i2gw/ingress2gateway.go
  pkg/i2gw/provider.go
  pkg/i2gw/providers/common/converter.go
  pkg/i2gw/providers/common/converter_test.go
  pkg/i2gw/providers/common/utils.go
  pkg/i2gw/providers/ingressnginx/canary.go
  pkg/i2gw/providers/ingressnginx/canary_test.go
  pkg/i2gw/providers/ingressnginx/converter_test.go
  pkg/i2gw/providers/istio/converter.go
  pkg/i2gw/providers/kong/converter_test.go
  pkg/i2gw/providers/kong/header_matching.go
  pkg/i2gw/providers/kong/header_matching_test.go
  pkg/i2gw/providers/kong/implementation_specific.go
  pkg/i2gw/providers/kong/method_matching.go
  pkg/i2gw/providers/kong/method_matching_test.go
  pkg/i2gw/providers/kong/plugins.go
  pkg/i2gw/providers/kong/utils_test.go
Labels: approved, size/XL, cncf-cla: yes, lgtm

#110 Print generated GatewayClasses, TLSRoutes, TCPRoutes and ReferenceGrants.
  cmd/print.go
  pkg/i2gw/ingress2gateway.go
Labels: kind/feature, approved, size/L, tide/merge-method-squash, cncf-cla: yes, lgtm

#112 Change ingress fetching to be isolated per provider
  pkg/i2gw/ingress2gateway.go
  pkg/i2gw/ingress2gateway_test.go
  pkg/i2gw/provider.go
  pkg/i2gw/providers/ingressnginx/converter.go
  pkg/i2gw/providers/ingressnginx/converter_test.go
  pkg/i2gw/providers/ingressnginx/ingressnginx.go
  pkg/i2gw/providers/ingressnginx/resource_reader.go
  pkg/i2gw/providers/ingressnginx/storage.go
  pkg/i2gw/providers/istio/istio.go
  pkg/i2gw/providers/istio/resource_reader.go
  pkg/i2gw/providers/kong/converter.go
  pkg/i2gw/providers/kong/converter_test.go
  pkg/i2gw/providers/kong/kong.go
  pkg/i2gw/providers/kong/resource_reader.go
  pkg/i2gw/providers/kong/storage.go
Labels: kind/feature, do-not-merge/hold, approved, tide/merge-method-merge, size/XL, cncf-cla: yes, lgtm

#114 Revert "per-provider-ingress-fetching-isolation"
  pkg/i2gw/ingress2gateway.go
  pkg/i2gw/ingress2gateway_test.go
  pkg/i2gw/provider.go
  pkg/i2gw/providers/ingressnginx/converter.go
  pkg/i2gw/providers/ingressnginx/converter_test.go
  pkg/i2gw/providers/ingressnginx/ingressnginx.go
  pkg/i2gw/providers/ingressnginx/resource_reader.go
  pkg/i2gw/providers/ingressnginx/storage.go
  pkg/i2gw/providers/istio/istio.go
  pkg/i2gw/providers/istio/resource_reader.go
  pkg/i2gw/providers/kong/converter.go
  pkg/i2gw/providers/kong/converter_test.go
  pkg/i2gw/providers/kong/kong.go
  pkg/i2gw/providers/kong/resource_reader.go
  pkg/i2gw/providers/kong/storage.go
Labels: approved, size/XL, cncf-cla: yes, lgtm
