Repository kubernetes-sigs/ingress2gateway, pull requests merged in 2023-10, with the labels that each got.

#70 i2gw binary added to .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, size/XS, lgtm

#61 Document the new release process
  .github/workflows/release.yaml
  .goreleaser.yaml
  CHANGELOG.md
  RELEASE.md
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#75 fix wording
  RELEASE.md
Labels: approved, kind/cleanup, cncf-cla: yes, size/XS, lgtm

#76 Adding changelog for v0.1.0-rc1
  .github/workflows/release.yaml
  CHANGELOG.md
Labels: approved, kind/documentation, cncf-cla: yes, size/XS, lgtm

#77 add installtion headline
  README.md
Labels: approved, kind/documentation, size/S, cncf-cla: yes, lgtm

#72 Kong plugins feature
  pkg/i2gw/providers/kong/README.md
  pkg/i2gw/providers/kong/annotations.go
  pkg/i2gw/providers/kong/converter.go
  pkg/i2gw/providers/kong/converter_test.go
  pkg/i2gw/providers/kong/method_matching_test.go
  pkg/i2gw/providers/kong/plugins.go
Labels: approved, size/L, cncf-cla: yes, lgtm

#82 change goreleaser to draft release
  .goreleaser.yaml
Labels: approved, cncf-cla: yes, size/XS, lgtm

#83 Adding changelog for v0.1.0
  CHANGELOG.md
Labels: approved, kind/documentation, size/S, cncf-cla: yes, lgtm
