Repository kubernetes-sigs/ingress2gateway, pull requests merged in 2024-08, with the labels that each got.

#176 added notifications for apisix provider
  pkg/i2gw/providers/apisix/http_to_https.go
  pkg/i2gw/providers/apisix/notification.go
Labels: kind/feature, approved, size/M, cncf-cla: yes, lgtm, ok-to-test

#177 added notifications for ingress-nginx provider
  pkg/i2gw/providers/ingressnginx/canary.go
  pkg/i2gw/providers/ingressnginx/notification.go
Labels: kind/feature, approved, size/M, cncf-cla: yes, lgtm, ok-to-test

#182 nginx: apply canary only for enabled rule groups
  pkg/i2gw/providers/ingressnginx/canary.go
  pkg/i2gw/providers/ingressnginx/converter_test.go
Labels: kind/bug, approved, size/L, cncf-cla: yes, lgtm

#184 release 0.3.0
  CHANGELOG.md
  README.md
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm
