Repository kubernetes-sigs/ingress2gateway, pull requests merged in 2024-12, with the labels that each got.

#204 add changelog for release 0.4.0-rc1
  CHANGELOG.md
Labels: approved, kind/documentation, size/S, cncf-cla: yes, lgtm

#205 fix typo
  README.md
Labels: approved, cncf-cla: yes, size/XS, lgtm

#207 fix/update .goreleaser.yaml file
  .goreleaser.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS, lgtm, ok-to-test
