Repository kubernetes-sigs/ingress2gateway, pull requests merged in 2024-01, with the labels that each got.

#104 fix: avoid duplicate `BackendRefs`
  pkg/i2gw/providers/common/converter.go
  pkg/i2gw/providers/common/converter_test.go
  pkg/i2gw/providers/common/utils.go
Labels: kind/bug, approved, size/L, tide/merge-method-squash, cncf-cla: yes, lgtm, ok-to-test

#116 [Revert the revert] Change ingress fetching to be isolated per provider
  pkg/i2gw/ingress2gateway.go
  pkg/i2gw/ingress2gateway_test.go
  pkg/i2gw/provider.go
  pkg/i2gw/providers/common/resource_reader.go
  pkg/i2gw/providers/common/resource_reader_test.go
  pkg/i2gw/providers/common/testdata/input-file.json
  pkg/i2gw/providers/common/testdata/input-file.yaml
  pkg/i2gw/providers/ingressnginx/converter.go
  pkg/i2gw/providers/ingressnginx/converter_test.go
  pkg/i2gw/providers/ingressnginx/ingressnginx.go
  pkg/i2gw/providers/ingressnginx/resource_reader.go
  pkg/i2gw/providers/ingressnginx/storage.go
  pkg/i2gw/providers/istio/istio.go
  pkg/i2gw/providers/istio/resource_reader.go
  pkg/i2gw/providers/kong/converter.go
  pkg/i2gw/providers/kong/converter_test.go
  pkg/i2gw/providers/kong/kong.go
  pkg/i2gw/providers/kong/resource_reader.go
  pkg/i2gw/providers/kong/storage.go
Labels: kind/feature, approved, size/XL, cncf-cla: yes, lgtm

#111 Add istio provider
  README.md
  cmd/print.go
  pkg/i2gw/providers/common/converter.go
  pkg/i2gw/providers/istio/README.md
  pkg/i2gw/providers/istio/converter.go
  pkg/i2gw/providers/istio/converter_test.go
  pkg/i2gw/providers/istio/e2e_file_converter_test.go
  pkg/i2gw/providers/istio/fixtures/input/1-gateway.yaml
  pkg/i2gw/providers/istio/fixtures/input/2-virtualservice-http.yaml
  pkg/i2gw/providers/istio/fixtures/input/3-virtualservice-tls.yaml
  pkg/i2gw/providers/istio/fixtures/input/4-virtualservice-tcp.yaml
  pkg/i2gw/providers/istio/fixtures/input/5-referencegrants.yaml
  pkg/i2gw/providers/istio/fixtures/input/6-virtualservice-http-rewrite.yaml
  pkg/i2gw/providers/istio/fixtures/output/1-gateway.yaml
  pkg/i2gw/providers/istio/fixtures/output/2-virtualservice-http.yaml
  pkg/i2gw/providers/istio/fixtures/output/3-virtualservice-tls.yaml
  pkg/i2gw/providers/istio/fixtures/output/4-virtualservice-tcp.yaml
  pkg/i2gw/providers/istio/fixtures/output/5-referencegrants.yaml
  pkg/i2gw/providers/istio/fixtures/output/6-virtualservice-http-rewrite.yaml
  pkg/i2gw/providers/istio/istio.go
  pkg/i2gw/providers/istio/types.go
Labels: kind/feature, approved, tide/merge-method-merge, size/XXL, cncf-cla: yes, lgtm

#108 feat: add initial support for Apache APISIX provider
  cmd/print.go
  pkg/i2gw/providers/apisix/README.md
  pkg/i2gw/providers/apisix/annotations.go
  pkg/i2gw/providers/apisix/apisix.go
  pkg/i2gw/providers/apisix/converter.go
  pkg/i2gw/providers/apisix/http_to_https.go
  pkg/i2gw/providers/apisix/http_to_https_test.go
  pkg/i2gw/providers/apisix/resource_reader.go
  pkg/i2gw/providers/apisix/storage.go
Labels: kind/feature, approved, size/XL, cncf-cla: yes, lgtm, ok-to-test

#119 Add changelog for release v0.2.0-rc1
  CHANGELOG.md
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#121 fix go version in release.yaml
  .github/workflows/release.yaml
Labels: approved, kind/cleanup, cncf-cla: yes, size/XS, lgtm

#126 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, size/XS, lgtm, ok-to-test

#128 Skip k8s client creation when reading local file.
  pkg/i2gw/ingress2gateway.go
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm
