Repository kubernetes-sigs/ingress2gateway, pull requests merged in 2024-11, with the labels that each got.

#200 Mark providers as required in documentation
  README.md
Labels: approved, kind/documentation, cncf-cla: yes, size/XS, lgtm

#197 Update README with latest supported features and references.
  pkg/i2gw/providers/gce/README.md
Labels: approved, kind/documentation, size/S, cncf-cla: yes, lgtm

#178 added notifications for openapi3 provider
  pkg/i2gw/providers/openapi3/converter.go
  pkg/i2gw/providers/openapi3/notification.go
Labels: kind/feature, approved, size/M, cncf-cla: yes, lgtm, ok-to-test
