Repository kubernetes-sigs/ingress2gateway, pull requests merged in 2024-04, with the labels that each got.

#149 move bowei and shaneutt to emeritus_approvers
  OWNERS
Labels: approved, size/S, cncf-cla: yes, lgtm

#137 fix: weight can not set to 0
  pkg/i2gw/providers/ingressnginx/canary.go
  pkg/i2gw/providers/ingressnginx/canary_test.go
Labels: kind/bug, approved, size/M, cncf-cla: yes, lgtm, ok-to-test

#139 fix flakly ingressnginx test
  pkg/i2gw/providers/ingressnginx/converter.go
  pkg/i2gw/providers/ingressnginx/converter_test.go
  pkg/i2gw/providers/ingressnginx/resource_reader.go
  pkg/i2gw/providers/ingressnginx/storage.go
Labels: kind/bug, approved, size/L, cncf-cla: yes, lgtm

#152 Improve error handling across kong & ingress-nginx
  pkg/i2gw/providers/common/converter.go
  pkg/i2gw/providers/ingressnginx/canary.go
  pkg/i2gw/providers/kong/converter.go
  pkg/i2gw/providers/kong/header_matching.go
  pkg/i2gw/providers/kong/method_matching.go
  pkg/i2gw/providers/kong/plugins.go
Labels: kind/bug, approved, size/M, cncf-cla: yes, lgtm

#153 fail soft when crds are not installed
  pkg/i2gw/providers/istio/resource_reader.go
  pkg/i2gw/providers/kong/resource_reader.go
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#155 [istio] fix: handle wildcard hosts in VirtualServices
  pkg/i2gw/providers/istio/converter.go
  pkg/i2gw/providers/istio/converter_test.go
Labels: kind/bug, approved, size/L, cncf-cla: yes, lgtm, ok-to-test
